report_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
    report should be detailed and contains any and all relevant information and more than 20 bullet points.
  expected_output: >
    A list with more than 20 bullet points of the most relevant information about {topic}
  agent: report_generator

blog_writing_task:
    description: >
      Conduct a thorough research about {topic}
      Make sure you find any interesting and relevant information given
      the current year is {current_year}.
      blog should be detailed and contains any and all relevant information and more than 20 bullet points.
    expected_output: >
      A list with more than 20 bullet points of the most relevant information about {topic}
    agent: blog_writer


  